export type UserRole = "SUPER_ADMIN" | "ADMIN" | "USER";
export const UserRole = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER",
} as const;

export type UserStatus = "ACTIVE" | "SUSPENDED" | "PENDING_VERIFICATION" | "DELETED";
export const UserStatus = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  DELETED: "DELETED",
} as const;

export type AuthProvider = "CREDENTIALS" | "GOOGLE" | "GITHUB" | "LINKEDIN";
export const AuthProvider = {
  CREDENTIALS: "CREDENTIALS",
  GOOGLE: "GOOGLE",
  GITHUB: "GITHUB",
  LINKEDIN: "LINKEDIN",
} as const;

export type NotificationType = "SYSTEM" | "ACCOUNT" | "SECURITY" | "ANNOUNCEMENT";
export const NotificationType = {
  SYSTEM: "SYSTEM",
  ACCOUNT: "ACCOUNT",
  SECURITY: "SECURITY",
  ANNOUNCEMENT: "ANNOUNCEMENT",
} as const;

export type AuditAction =
  | "USER_LOGIN"
  | "USER_LOGOUT"
  | "USER_REGISTER"
  | "USER_PASSWORD_CHANGE"
  | "USER_PROFILE_UPDATE"
  | "USER_EMAIL_UPDATE"
  | "USER_AVATAR_UPDATE"
  | "USER_SUSPENDED"
  | "USER_ACTIVATED"
  | "USER_DELETED"
  | "USER_ROLE_CHANGED"
  | "USER_EMAIL_VERIFIED"
  | "ADMIN_ACTION"
  | "SETTINGS_CHANGED"
  | "FAILED_LOGIN";

export const AuditAction = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_REGISTER: "USER_REGISTER",
  USER_PASSWORD_CHANGE: "USER_PASSWORD_CHANGE",
  USER_PROFILE_UPDATE: "USER_PROFILE_UPDATE",
  USER_EMAIL_UPDATE: "USER_EMAIL_UPDATE",
  USER_AVATAR_UPDATE: "USER_AVATAR_UPDATE",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DELETED: "USER_DELETED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_EMAIL_VERIFIED: "USER_EMAIL_VERIFIED",
  ADMIN_ACTION: "ADMIN_ACTION",
  SETTINGS_CHANGED: "SETTINGS_CHANGED",
  FAILED_LOGIN: "FAILED_LOGIN",
} as const;
